variables:
  # Feel free to choose the image that suits you best.
  # blang/latex:latest ... Former image used in this template. No longer maintained by author.
  # listx/texlive:2020 ... The default, referring to TexLive 2020. Current at least to 2021-02-02.

  # Additional alternatives with high Docker pull counts:
  # thomasweise/docker-texlive-full
  # thomasweise/texlive
  # adnrv/texlive
  LATEX_IMAGE: thomasweise/docker-texlive-full
  PYTHON_IMAGE: python:3.6.6

stages:
  - build

build_blaetter:
  stage: build
  image: $LATEX_IMAGE
  script:
    - make UBlaetter_ci
  artifacts:
    name: "UeIDB_Blaetter"
    paths:
      - "Blaetter"
    expire_in:
      40 days

build_folien:
  stage: build
  image: $LATEX_IMAGE
  script:
    - make UFolien_ci
  artifacts:
    name: "UeIDB_Folien"
    paths:
      - "Folien"
    expire_in:
      40 days
